<!DOCTYPE html><html lang="es"><head><meta charset="utf-8" /><title>Cómo manejar excepciones en Clojure – Avanzado</title><meta content="El manejo de excepciones en Clojure permite capturar y gestionar errores mediante las funciones try, catch y finally. Además, Clojure ofrece herramientas para crear excepciones personalizadas." name="description" /><link href="/../../styles.css" rel="stylesheet" /><meta content="initial-scale=1, width=device-width" name="viewport" /><meta content="NEdWFaLiY4F7Mnw5exM0mj9XLjyr9mJ5VFtGVqjBeWA" name="google-site-verification" /><script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"Cómo manejar excepciones en Clojure – Avanzado","description":"El manejo de excepciones en Clojure permite capturar y gestionar errores mediante las funciones try, catch y finally. Además, Clojure ofrece herramientas para crear excepciones personalizadas.\n         Crear excepciones personalizadas\n         Con ex-info, podemos lanzar excepciones que contienen más detalles sobre el error:\n         (throw (ex-info \"Algo salió mal\" {:codigo 400}))\n         Capturar excepciones\n         Usamos catch para capturar excepciones y manejarlas de forma específica:\n         (try\n  ...\n  (catch Exception e\n    (println \"Error:\" (.getMessage e))))"}</script><meta content="ca-pub-4545173212980791" name="google-adsense-account" /></head><script async="async" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4545173212980791"></script></html><body><div id="app"></div><main><article><h1>Cómo manejar excepciones en Clojure – Avanzado</h1><p>El manejo de excepciones en Clojure permite capturar y gestionar errores mediante las funciones <code>try</code>, <code>catch</code> y <code>finally</code>. Además, Clojure ofrece herramientas para crear excepciones personalizadas.</p>
         <h2>Crear excepciones personalizadas</h2>
         <p>Con <code>ex-info</code>, podemos lanzar excepciones que contienen más detalles sobre el error:</p>
         <code>(throw (ex-info "Algo salió mal" {:codigo 400}))</code>
         <h2>Capturar excepciones</h2>
         <p>Usamos <code>catch</code> para capturar excepciones y manejarlas de forma específica:</p>
         <code>(try
  ...
  (catch Exception e
    (println "Error:" (.getMessage e))))</code></article></main><footer class="footer"><div class="footer-content"><ul class="footer-links"><li><a class="footer-link" href="/politica-de-cookies">Política de Cookies</a></li><li><a class="footer-link" href="/politica-de-privacidad">Política de Privacidad</a></li><li><a class="footer-link" href="/sobre-nosotros">Sobre Nosotros</a></li></ul><div class="footer-note deaccept-cookies"><button id="unaccept-cookies">Deshacer aceptación de cookies</button></div></div><p class="footer-note">Última actualización: 14 de diciembre de 2024</p></footer><script defer="defer" src="/js/compiled/app.js"></script></body>